apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-deployment
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
        api: external  
    spec:
      containers:
      - image: wassimmayyasi/udagram-frontend:v2
        name: udagram-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"   
        ports:
        - containerPort: 80
      restartPolicy: Always